### ISSUE TITLE
Very nice :)

### ISSUE THREAD

**Issue by photonstorm** [vinod8990/Phaser_Multiscreen_Example#1]
Nice example (and tutorial to go with it on your site). Would you mind dropping me an email? (rdavey at gmail dot com) so we could have a quick chat about this code. Basically I'd like to find a way to support it natively, so you don't need to patch it in, and also get some feedback on further screen handling ideas we've got.

Cheers,

Rich

**Comment by jdnichollsc** [comment]
@photonstorm any news about this? to support multiscreen natively on Phaser? :dancers:

**Comment by photonstorm** [comment]
@jdnichollsc nope, nothing ever happened. This code is super old now, so maybe not even that easy to implement any more.

**Comment by jdnichollsc** [comment]
@photonstorm I would like to help to implement this feature... because is very important to Phaser! For example... to work with CocoonJS =)

**Comment by photonstorm** [comment]
I see so many games released with Cocoon each week that this feature obviously isn't _required_. Even so, if you want to implement it, and it doesn't change the API too much, I'll gladly merge it.

**Comment by jdnichollsc** [comment]
See Rich @photonstorm  https://github.com/vinod8990/phaser-2.4.2-multiscreen

**Comment by photonstorm** [comment]
I need a PR against phaser dev branch, can merge from there (I assume this would be a new Project Template, rather than any actual change to Phaser?)
